### ISSUE TITLE
Improve the images display code

### ISSUE THREAD

**Issue by slzakaria** [Zackaria-Slimane/unFetch#1]
Make the images always take the same space on grid  or change to flex , up to you !

**Comment by mhdamaan79** [comment]
I would like to work on this issue. Please assign this issue to me.

**Comment by VishnuAmit** [comment]
I am familiar with this. Looking forward to contribute to your amazing image generating web app :)

**Comment by slzakaria** [comment]
> I would like to work on this issue. Please assign this issue to me.

Sure buddy ! gl

**Comment by slzakaria** [comment]
@mhdamaan79 Great work !
