### ISSUE TITLE
Add dark/light mode toggle 

### ISSUE THREAD

**Issue by slzakaria** [Zackaria-Slimane/unFetch#2]
Add a working dark to light mode toggle with correct theme colors

**Comment by bharath090909** [comment]
@Zackaria-Slimane can I take up this issue ?

**Comment by slzakaria** [comment]
> @Zackaria-Slimane can I take up this issue ?

Sure , Have fun !

**Comment by bharath090909** [comment]
@Zackaria-Slimane I'm getting status code 401 when fetching data from API. I think you need to give permission to read photos by giving access to unsplash API key.

**Comment by bharath090909** [comment]
@Zackaria-Slimane Completed the task and raised PR, please check and let me know if any changes required. Thanks for the opportunity 😁.

**Comment by bharath090909** [comment]
@Zackaria-Slimane Completed dark mode implementation and raised PR please check and let me know if any changes required. Thanks for the opportunity.

**Comment by Kedarnath-Rothe** [comment]
Please assign this issue to me

**Comment by slzakaria** [comment]
> Please assign this issue to me

Go ahead !

**Comment by Bib3k4u** [comment]
Can I work on this??

**Comment by slzakaria** [comment]
> Can I work on this??

@Bib3k4u  Go ahead !

**Comment by Bib3k4u** [comment]
Add dark/light mode toggle #2 
Added and Implemented and raised a PR please check it

**Comment by slzakaria** [comment]
@Bib3k4u Great work, closing the issue
