### ISSUE TITLE
Fix pagination not working on manual query 

### ISSUE THREAD

**Issue by slzakaria** [Zackaria-Slimane/unFetch#8]
When chosing a query from the 4 presets the pagination of results works as inteded, how ever when you input your query and try to change pages it stays on page 1.

**Comment by Baburao-sanivada** [comment]
EveryThing Is Working properly What is the Issue Can you provide some more Description

**Comment by slzakaria** [comment]
> EveryThing Is Working properly What is the Issue Can you provide some more Description

Write something to search, when the images load try to go to the bottom of the page and click Next page, currently it does nothing. Next and previous only works if you select one of the 4 presets

**Comment by Baburao-sanivada** [comment]
I will Work On It Assign me the Issue

**Comment by Kokonodray2001** [comment]
can you assign me this issue?

**Comment by slzakaria** [comment]
> can you assign me this issue?

Go ahead , goodluck !

**Comment by Kokonodray2001** [comment]
@Zackaria-Slimane  please check the PR. i suppose the issue is resolved  ffa4421b65997a0c83a954e79912184522db9759

**Comment by slzakaria** [comment]
Well done @Kokonodray2001
