### ISSUE TITLE
Add an explicit Submit - Search Button to the search bar 

### ISSUE THREAD

**Issue by slzakaria** [Zackaria-Slimane/unFetch#9]
Currently it is not clear that the search can be submitted by just pressing enter , it would be better if there was a explicit button to click on for search

**Comment by Baburao-sanivada** [comment]
I Would like to Work on this Issue

**Comment by vd89** [comment]
- Would like to know more about the task so can do the implementation 
- and provide the out come as well 
- would like to take this issue

**Comment by Bib3k4u** [comment]
I would like to work on this Issue

**Comment by Bib3k4u** [comment]
@Zackaria-Slimane This is the first time I have raised a PR and my Apology if I created any issue.
Please check I have added the Search Button and raised a PR.

**Comment by slzakaria** [comment]
> @Zackaria-Slimane This is the first time I have raised a PR and my Apology if I created any issue. Please check I have added the Search Button and raised a PR.

Thanks for the pr ! i hope you enjoyed the process, i left you a comment in the pr . Happy hacktoberfesting !
